// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using taskfinalfor_.db;

#nullable disable

namespace taskfinalforC_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250602044348_udateOrders")]
    partial class udateOrders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("taskfinalforC_.db.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Jewelry"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Video Games"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Home Decor"
                        });
                });

            modelBuilder.Entity("taskfinalforC_.db.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Nino Beridze",
                            OrderDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Giorgi Mikeladze",
                            OrderDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Lasha Kapanadze",
                            OrderDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Salome Gagnidze",
                            OrderDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 9,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 5,
                            CustomerName = "Ana Chikhladze",
                            OrderDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            CustomerName = "Nikoloz Tsertsvadze",
                            OrderDate = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            CustomerName = "Lizi Tabidze",
                            OrderDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 8,
                            CustomerName = "Mariam Shengelia",
                            OrderDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 12,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            CustomerName = "Dato Mchedlishvili",
                            OrderDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            CustomerName = "Eka Kapanadze",
                            OrderDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 11,
                            CustomerName = "Gela Chanturia",
                            OrderDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 12,
                            CustomerName = "Tatia Kvantaliani",
                            OrderDate = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 13,
                            CustomerName = "Beka Tsikarishvili",
                            OrderDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 13,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 14,
                            CustomerName = "Elene Akhvlediani",
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 14,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 15,
                            CustomerName = "Irakli Gelashvili",
                            OrderDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 15,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 16,
                            CustomerName = "Lali Papashvili",
                            OrderDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 16,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 17,
                            CustomerName = "Zaza Giorgadze",
                            OrderDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 18,
                            CustomerName = "Maia Metreveli",
                            OrderDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 18,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 19,
                            CustomerName = "Tamar Kukava",
                            OrderDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 19,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 20,
                            CustomerName = "Natia Lomtatidze",
                            OrderDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 20,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("taskfinalforC_.db.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 899m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Sci-Fi Novel",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Children's Book",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "T-Shirt",
                            Price = 25m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Jacket",
                            Price = 60m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Lego Set",
                            Price = 45m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Board Game",
                            Price = 35m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Milk",
                            Price = 3m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Name = "Eggs",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Name = "Chair",
                            Price = 80m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Name = "Desk",
                            Price = 150m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Name = "Football",
                            Price = 20m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Name = "Tennis Racket",
                            Price = 75m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Name = "Vitamin C",
                            Price = 10m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 9,
                            Name = "Shampoo",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 10,
                            Name = "Car Oil",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 11,
                            Name = "Dog Food",
                            Price = 40m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 13,
                            Name = "Guitar",
                            Price = 300m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 20,
                            Name = "Wall Clock",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("taskfinalforC_.db.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PAssword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PAssword = "admin123",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("taskfinalforC_.db.Order", b =>
                {
                    b.HasOne("taskfinalforC_.db.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("taskfinalforC_.db.Product", b =>
                {
                    b.HasOne("taskfinalforC_.db.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("taskfinalforC_.db.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
